### PR TITLE
user issues

### PR DESCRIPTION
**Pull request by werty144**

### CODE REVIEW

**Review by M0nsteR — CHANGES_REQUESTED** [review]
The formalism of your initial set of user stories needs revision. Please study some general recommendations and resources on this topic: https://www.atlassian.com/agile/project-management/user-stories
and try to follow the accepted formalisms.

**Comment by M0nsteR** [comment]
Please note that every user story should have a numeric id so that we could refer to any one of them later on.

**Comment by M0nsteR** [comment]
Please fix a typo in #5 ("не знаю пароля"). Anothing thing, the filename 'issues.md' is not quite helpful, for it implies some problematic behaviour in your code. I'd suggest using the same name as you have as a title of this document, just stories or user-stories.md.

**Comment by M0nsteR** [comment]
Are you sure that #6 and #7 aren't the same functionality?

**Comment by egdegd** [comment]
@M0nsteR, fixed

**Review by M0nsteR — APPROVED** [review]

**Comment by M0nsteR** [comment]
OK, let's call it a day. To be discussed and refined later on.

**Pull request merged**
